services:
  rag_backend:
    build:
      context: .
      dockerfile: docker/DockerFile.be
      cache_from:
        - rag_backend:latest
    container_name: rag_backend
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    env_file:
      - ./apps/backend/.env
    depends_on:
      - db
      - chroma

  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - rag_docs_data:/data/chromadb
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - rag_docs_data:/var/lib/postgresql

volumes:
  rag_docs_data:
